#!/usr/bin/env bash
# Display "bad luck" and "good luck"  for 4th and 8th iteration respectively  and "Best school" for others
i=1
while [ "$i" -le 10 ]
do 
      echo "Best School"
      if [ "$i" -eq 4 ]
      then 
         echo "bad luck" 
      elif [ "$i" -eq 8 ]
      then 
           echo "good luck"
      fi 
      i=$((i + 1))
done
